### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by d1ma4ek** [WillYeadon/gtawFOAM#1]
Hello. Could you help with installation? I have an error during installation.
Is there an example solution tutorial?

**Comment by WillYeadon** [comment]
Are you using OpenFoam6? It is what the solver was written in, I'm not sure how well it will work with other versions as I haven't tried it with them. In principle, to install it you put the gtawFOAM folder into your user directory then run wclean and wmake.

**Comment by d1ma4ek** [comment]
Hi. when unpacking, I get the following error

In file included from incompressibleThreePhaseMixture/incompressible Three Phase Mixture.C:26:0:
incompressibleThreePhaseMixture/incompressibleThreePhaseMixture.H:37:10: fatal error: kinematicTransportModel.H: There is no such file or directory
#include "kinematicTransportModel.H"



UBUNTU version 18.04,
Open foam
Usage: OpenFOAM-6 (watch www.OpenFOAM.org )
Reference: 6-47517f2ebb1b

**Comment by WillYeadon** [comment]
Okay it looks like you used the same version as me but the compiler isn't finding the transportModels header file. The second line of Make/options file should find this in "    -I$(LIB_SRC)/transportModels/lnInclude \". Do you have multiple version of OpenFOAM installed? It might be the case that you have sourced another version and I$(LIB_SRC) could be pointing towards say OpenFoam9?

**Comment by d1ma4ek** [comment]
Hi. Thanks for the reply.
Yes, I have other versions of OpenFOAM. How to use the I$(LIB_SRC) handout?
I managed to install thesis
only the cases did not start. What could I have done wrong? The order of commands performed at startup

cpr initial 0
blockMesh
sets
decomposePar

**Comment by d1ma4ek** [comment]
OK, I seem to understand what the error is, can I specify the path manually in make?

**Comment by WillYeadon** [comment]
You can but you'll probably need to do this for all the included header files. Instead you can source OpenFOAM6 bashrc by the terminal command 'source /opt/openfoam6/etc/bashrc' this will update all of your environment variables so that I$(LIB_SRC) and others point to the correct location.

Also, to run the cases just use 'gtawFoam' on its own so that you can see if it runs at all before you try to parallelize it.  Just copy the case files into your 'run' directory and then in the terminal use the commands 'setFields', 'blockMesh' and then 'gtawFoam' on their own.

**Comment by d1ma4ek** [comment]
I'm sorry, I copied the solver launch from another example. Okay, I just don't even get to the parallelize stage, the errors are already at the set Fields stage.

Forgive me, but my Bashrc is on a completely different path /OpenFOAM/OpenFOAM-6/etc
what should I do with it? How is Bashrc edited or did I get something wrong?

Maybe I'm asking too banal questions, but I'm still a beginner.

**Comment by WillYeadon** [comment]
Okay so your Ubuntu distribution has a main bashrc that you can edit using 'emacs ~/.bashrc' where emacs is whatever text editor you're using (so if you're using sublime you'd type 'subl ~/.bashrc' into the terminal). If you have Openfoam installed, at the bottom of the bashrc file you'll see something along the lines of 'source /opt/openfoam...'. If you have multiple versions of Openfoam there is a chance that the 'source' commands are overwriting each other which is why 'I$(LIB_SRC)' can't find 'kinematicTransportModels.H' as you may have sourced another version of OpenFoam where 'kinematicTransportModels.H' is either non-existent or in another location. The easiest fix for this is to make sure the last line of your bashrc file reads 'source /opt/openfoam6/etc/bashrc' so that Openfoam6 will be sourced. You can then use the 'source ~/.bashrc' command to do this. This _should_ mean that 'I$(LIB_SRC)' points to where 'kinematicTransportModels.H' is.

**Comment by d1ma4ek** [comment]
Yes, I double-checked it again, and I always edit it when switching from version to version, with the command gedit ~/.bashrc. The path is specified as follows
source $HOME/OpenFOAM/OpenFOAM-6/etc/bashrc.
Thanks for the help, apparently I don't understand something, but what should the title look like in my case in make?

$HOME/OpenFOAM/OpenFOAM-6/etc/bashrc/MomentumTransportModels/incompressible/lnInclude


my openfoam 6 is not installed in the opt folder because at the moment installation via the terminal of this version is no longer supported. The installation was carried out according to this guide https://openfoamwiki.net/index.php/Installation/Linux/OpenFOAM-6/Ubuntu
Thanks for the help, I think I figured out what I have to do.

**Comment by WillYeadon** [comment]
Okay great, so the make/options should be the same as in the repo as with the correct environment variables they should be pointing to the right place. From your comment I assume this is okay now? I there are still issues feel free to open another ticket.
